In [2]:
import os

print(os.getcwd())

c:\Users\HI\Desktop\intern\-Smart-Energy-Consumption-Prediction-System\clustering\notebooks

In [3]:
import pandas as pd

df = pd.read_csv(
    "../../data/processed/feature_engineered_energy_data.csv"
)

df.head()

,DateTime,Temperature,Humidity,Wind_Speed,General_Diffuse_Flows,Diffuse_Flows,Zone_1_Power_Consumption,Zone_2_Power_Consumption,Zone_3_Power_Consumption,Hour,...,Zone_3_roll_max_1h,Zone_3_roll_mean_24h,Zone_3_roll_std_24h,Zone_3_roll_min_24h,Zone_3_roll_max_24h,Temp_Humidity_Index,Season_Autumn,Season_Spring,Season_Summer,Season_Winter
0,2017-01-01 00:00:00,6.559,73.8,0.083,0.051,0.119,34055.69620,16128.87538,20240.96386,0,...,NaN,NaN,NaN,NaN,NaN,-23.858374,False,False,False,True
1,2017-01-01 00:10:00,6.414,74.5,0.083,0.070,0.085,29814.68354,19375.07599,20131.08434,0,...,20240.96386,20240.963860,NaN,20240.96386,20240.96386,-24.599243,False,False,False,True
2,2017-01-01 00:20:00,6.313,74.5,0.080,0.062,0.100,29128.10127,19006.68693,19668.43373,0,...,20240.96386,20186.024100,77.696554,20131.08434,20240.96386,-24.951034,False,False,False,True
3,2017-01-01 00:30:00,6.121,75.0,0.083,0.091,0.096,28228.86076,18361.09422,18899.27711,0,...,20240.96386,20013.493977,303.839279,19668.43373,20240.96386,-25.795530,False,False,False,True
4,2017-01-01 00:40:00,5.921,75.7,0.081,0.048,0.085,27335.69620,17872.34043,18442.40964,0,...,20240.96386,19734.939760,609.848625,18899.27711,20240.96386,-26.746187,False,False,False,True

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 52416 entries, 0 to 52415
Data columns (total 53 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   DateTime                  52416 non-null  str
 1   Temperature               52416 non-null  float64
 2   Humidity                  52416 non-null  float64
 3   Wind_Speed                52416 non-null  float64
 4   General_Diffuse_Flows     52416 non-null  float64
 5   Diffuse_Flows             52416 non-null  float64
 6   Zone_1_Power_Consumption  52416 non-null  float64
 7   Zone_2_Power_Consumption  52416 non-null  float64
 8   Zone_3_Power_Consumption  52416 non-null  float64
 9   Hour                      52416 non-null  int64
 10  Day_of_Week               52416 non-null  int64
 11  Month                     52416 non-null  int64
 12  Quarter                   52416 non-null  int64
 13  Is_Weekend                52416 non-null  int64
 14  Is_Peak_Hour              52416 non-null  int64
 15  Zone_1_lag_1              52415 non-null  float64
 16  Zone_1_lag_6              52410 non-null  float64
 17  Zone_1_lag_144            52272 non-null  float64
 18  Zone_2_lag_1              52415 non-null  float64
 19  Zone_2_lag_6              52410 non-null  float64
 20  Zone_2_lag_144            52272 non-null  float64
 21  Zone_3_lag_1              52415 non-null  float64
 22  Zone_3_lag_6              52410 non-null  float64
 23  Zone_3_lag_144            52272 non-null  float64
 24  Zone_1_roll_mean_1h       52415 non-null  float64
 25  Zone_1_roll_std_1h        52414 non-null  float64
 26  Zone_1_roll_min_1h        52415 non-null  float64
 27  Zone_1_roll_max_1h        52415 non-null  float64
 28  Zone_1_roll_mean_24h      52415 non-null  float64
 29  Zone_1_roll_std_24h       52414 non-null  float64
 30  Zone_1_roll_min_24h       52415 non-null  float64
 31  Zone_1_roll_max_24h       52415 non-null  float64
 32  Zone_2_roll_mean_1h       52415 non-null  float64
 33  Zone_2_roll_std_1h        52414 non-null  float64
 34  Zone_2_roll_min_1h        52415 non-null  float64
 35  Zone_2_roll_max_1h        52415 non-null  float64
 36  Zone_2_roll_mean_24h      52415 non-null  float64
 37  Zone_2_roll_std_24h       52414 non-null  float64
 38  Zone_2_roll_min_24h       52415 non-null  float64
 39  Zone_2_roll_max_24h       52415 non-null  float64
 40  Zone_3_roll_mean_1h       52415 non-null  float64
 41  Zone_3_roll_std_1h        52414 non-null  float64
 42  Zone_3_roll_min_1h        52415 non-null  float64
 43  Zone_3_roll_max_1h        52415 non-null  float64
 44  Zone_3_roll_mean_24h      52415 non-null  float64
 45  Zone_3_roll_std_24h       52414 non-null  float64
 46  Zone_3_roll_min_24h       52415 non-null  float64
 47  Zone_3_roll_max_24h       52415 non-null  float64
 48  Temp_Humidity_Index       52416 non-null  float64
 49  Season_Autumn             52416 non-null  bool
 50  Season_Spring             52416 non-null  bool
 51  Season_Summer             52416 non-null  bool
 52  Season_Winter             52416 non-null  bool
dtypes: bool(4), float64(42), int64(6), str(1)
memory usage: 19.8 MB

In [5]:
df.describe()

,Temperature,Humidity,Wind_Speed,General_Diffuse_Flows,Diffuse_Flows,Zone_1_Power_Consumption,Zone_2_Power_Consumption,Zone_3_Power_Consumption,Hour,Day_of_Week,...,Zone_2_roll_max_24h,Zone_3_roll_mean_1h,Zone_3_roll_std_1h,Zone_3_roll_min_1h,Zone_3_roll_max_1h,Zone_3_roll_mean_24h,Zone_3_roll_std_24h,Zone_3_roll_min_24h,Zone_3_roll_max_24h,Temp_Humidity_Index
count,52416.000000,52416.000000,52416.000000,52416.000000,52416.000000,52416.000000,52416.000000,52416.000000,52416.000000,52416.000000,...,52415.000000,52415.000000,52414.000000,52415.000000,52415.000000,52415.000000,52414.000000,52415.000000,52415.000000,52416.000000
mean,18.810024,68.259518,1.959489,182.696614,75.028022,32344.970564,21042.471746,17737.319088,11.500000,3.000000,...,28913.584734,17737.690047,458.099102,17145.986519,18330.188545,17742.181233,4163.269281,10773.948364,25502.837077,16.744079
std,5.815476,15.551177,2.348862,264.400960,124.210949,7130.562564,5201.353750,6320.262786,6.922253,2.000019,...,3591.388351,6290.791748,485.939337,6206.476552,6388.732232,4675.272507,919.237725,2796.230543,5526.529685,17.915570
min,3.247000,11.340000,0.050000,0.004000,0.011000,13895.696200,8560.081466,5935.174070,0.000000,0.000000,...,16128.875380,6132.052821,0.000000,5935.174070,6275.150060,10453.581433,77.696554,5935.174070,15195.198080,-39.163665
25%,14.410000,58.310000,0.078000,0.062000,0.122000,26310.668692,16980.766032,13129.326630,5.750000,1.000000,...,26239.513680,13127.829039,148.897176,12539.729210,13727.677215,14281.195897,3212.081057,8984.187947,20474.770170,3.572755
50%,18.780000,69.860000,0.086000,5.035500,4.456000,32265.920340,20823.168405,16415.117470,11.500000,3.000000,...,28329.483280,16423.132530,299.537967,15974.400000,16863.195980,17407.477017,4281.170068,10617.831330,25943.132530,18.224656
75%,22.890000,81.400000,4.915000,319.600000,101.000000,37309.018185,24713.717520,21624.100420,17.250000,5.000000,...,31803.167900,21621.815365,577.258700,20425.104600,22777.916820,18986.317327,4849.345903,11485.090910,28321.476920,30.400693
max,40.010000,94.800000,6.483000,1163.000000,936.000000,52204.395120,36313.144751,34366.261105,23.000000,6.000000,...,36313.144751,34366.261105,3582.814758,34366.261105,34366.261105,30835.230654,6663.104799,20304.602510,34366.261105,58.529350

In [6]:
drop_columns = [
    "DateTime"
]

In [7]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv(
    "../../data/processed/feature_engineered_energy_data.csv"
)

df.head()

,DateTime,Temperature,Humidity,Wind_Speed,General_Diffuse_Flows,Diffuse_Flows,Zone_1_Power_Consumption,Zone_2_Power_Consumption,Zone_3_Power_Consumption,Hour,...,Zone_3_roll_max_1h,Zone_3_roll_mean_24h,Zone_3_roll_std_24h,Zone_3_roll_min_24h,Zone_3_roll_max_24h,Temp_Humidity_Index,Season_Autumn,Season_Spring,Season_Summer,Season_Winter
0,2017-01-01 00:00:00,6.559,73.8,0.083,0.051,0.119,34055.69620,16128.87538,20240.96386,0,...,NaN,NaN,NaN,NaN,NaN,-23.858374,False,False,False,True
1,2017-01-01 00:10:00,6.414,74.5,0.083,0.070,0.085,29814.68354,19375.07599,20131.08434,0,...,20240.96386,20240.963860,NaN,20240.96386,20240.96386,-24.599243,False,False,False,True
2,2017-01-01 00:20:00,6.313,74.5,0.080,0.062,0.100,29128.10127,19006.68693,19668.43373,0,...,20240.96386,20186.024100,77.696554,20131.08434,20240.96386,-24.951034,False,False,False,True
3,2017-01-01 00:30:00,6.121,75.0,0.083,0.091,0.096,28228.86076,18361.09422,18899.27711,0,...,20240.96386,20013.493977,303.839279,19668.43373,20240.96386,-25.795530,False,False,False,True
4,2017-01-01 00:40:00,5.921,75.7,0.081,0.048,0.085,27335.69620,17872.34043,18442.40964,0,...,20240.96386,19734.939760,609.848625,18899.27711,20240.96386,-26.746187,False,False,False,True

In [9]:
df.columns.tolist()

['DateTime',
 'Temperature',
 'Humidity',
 'Wind_Speed',
 'General_Diffuse_Flows',
 'Diffuse_Flows',
 'Zone_1_Power_Consumption',
 'Zone_2_Power_Consumption',
 'Zone_3_Power_Consumption',
 'Hour',
 'Day_of_Week',
 'Month',
 'Quarter',
 'Is_Weekend',
 'Is_Peak_Hour',
 'Zone_1_lag_1',
 'Zone_1_lag_6',
 'Zone_1_lag_144',
 'Zone_2_lag_1',
 'Zone_2_lag_6',
 'Zone_2_lag_144',
 'Zone_3_lag_1',
 'Zone_3_lag_6',
 'Zone_3_lag_144',
 'Zone_1_roll_mean_1h',
 'Zone_1_roll_std_1h',
 'Zone_1_roll_min_1h',
 'Zone_1_roll_max_1h',
 'Zone_1_roll_mean_24h',
 'Zone_1_roll_std_24h',
 'Zone_1_roll_min_24h',
 'Zone_1_roll_max_24h',
 'Zone_2_roll_mean_1h',
 'Zone_2_roll_std_1h',
 'Zone_2_roll_min_1h',
 'Zone_2_roll_max_1h',
 'Zone_2_roll_mean_24h',
 'Zone_2_roll_std_24h',
 'Zone_2_roll_min_24h',
 'Zone_2_roll_max_24h',
 'Zone_3_roll_mean_1h',
 'Zone_3_roll_std_1h',
 'Zone_3_roll_min_1h',
 'Zone_3_roll_max_1h',
 'Zone_3_roll_mean_24h',
 'Zone_3_roll_std_24h',
 'Zone_3_roll_min_24h',
 'Zone_3_roll_max_24h',
 'Temp_Humidity_Index',
 'Season_Autumn',
 'Season_Spring',
 'Season_Summer',
 'Season_Winter']

In [10]:
cluster_features = [
    "Temperature",
    "Humidity",
    "Zone_1_Power_Consumption",
    "Zone_2_Power_Consumption",
    "Zone_3_Power_Consumption",
    "Hour",
    "Day_of_Week",
    "Month",
    "Is_Weekend",
    "Is_Peak_Hour"
]

cluster_df = df[cluster_features]

In [11]:
cluster_df.head()

,Temperature,Humidity,Zone_1_Power_Consumption,Zone_2_Power_Consumption,Zone_3_Power_Consumption,Hour,Day_of_Week,Month,Is_Weekend,Is_Peak_Hour
0,6.559,73.8,34055.69620,16128.87538,20240.96386,0,6,1,1,0
1,6.414,74.5,29814.68354,19375.07599,20131.08434,0,6,1,1,0
2,6.313,74.5,29128.10127,19006.68693,19668.43373,0,6,1,1,0
3,6.121,75.0,28228.86076,18361.09422,18899.27711,0,6,1,1,0
4,5.921,75.7,27335.69620,17872.34043,18442.40964,0,6,1,1,0

In [12]:
cluster_df.isnull().sum()

Temperature                 0
Humidity                    0
Zone_1_Power_Consumption    0
Zone_2_Power_Consumption    0
Zone_3_Power_Consumption    0
Hour                        0
Day_of_Week                 0
Month                       0
Is_Weekend                  0
Is_Peak_Hour                0
dtype: int64

In [13]:
cluster_df.to_csv(
    "../outputs/clustering_ready_dataset.csv",
    index=False
)

In [14]:
cluster_features = [

    # Weather influence
    "Temperature",
    "Humidity",
    "Wind_Speed",

    # Main energy consumption
    "Zone_1_Power_Consumption",
    "Zone_2_Power_Consumption",
    "Zone_3_Power_Consumption",

    # Time behaviour
    "Hour",
    "Day_of_Week",
    "Month",
    "Is_Weekend",
    "Is_Peak_Hour",

    # Recent consumption behaviour
    "Zone_1_lag_1",
    "Zone_2_lag_1",
    "Zone_3_lag_1",

    # Daily consumption trends
    "Zone_1_roll_mean_24h",
    "Zone_2_roll_mean_24h",
    "Zone_3_roll_mean_24h"

]

In [15]:
cluster_df = df[cluster_features]

cluster_df.head()

,Temperature,Humidity,Wind_Speed,Zone_1_Power_Consumption,Zone_2_Power_Consumption,Zone_3_Power_Consumption,Hour,Day_of_Week,Month,Is_Weekend,Is_Peak_Hour,Zone_1_lag_1,Zone_2_lag_1,Zone_3_lag_1,Zone_1_roll_mean_24h,Zone_2_roll_mean_24h,Zone_3_roll_mean_24h
0,6.559,73.8,0.083,34055.69620,16128.87538,20240.96386,0,6,1,1,0,NaN,NaN,NaN,NaN,NaN,NaN
1,6.414,74.5,0.083,29814.68354,19375.07599,20131.08434,0,6,1,1,0,34055.69620,16128.87538,20240.96386,34055.696200,16128.875380,20240.963860
2,6.313,74.5,0.080,29128.10127,19006.68693,19668.43373,0,6,1,1,0,29814.68354,19375.07599,20131.08434,31935.189870,17751.975685,20186.024100
3,6.121,75.0,0.083,28228.86076,18361.09422,18899.27711,0,6,1,1,0,29128.10127,19006.68693,19668.43373,30999.493670,18170.212767,20013.493977
4,5.921,75.7,0.081,27335.69620,17872.34043,18442.40964,0,6,1,1,0,28228.86076,18361.09422,18899.27711,30306.835442,18217.933130,19734.939760

In [16]:
cluster_df.shape

(52416, 17)

In [17]:
cluster_df.isnull().sum()

Temperature                 0
Humidity                    0
Wind_Speed                  0
Zone_1_Power_Consumption    0
Zone_2_Power_Consumption    0
Zone_3_Power_Consumption    0
Hour                        0
Day_of_Week                 0
Month                       0
Is_Weekend                  0
Is_Peak_Hour                0
Zone_1_lag_1                1
Zone_2_lag_1                1
Zone_3_lag_1                1
Zone_1_roll_mean_24h        1
Zone_2_roll_mean_24h        1
Zone_3_roll_mean_24h        1
dtype: int64

In [18]:
cluster_df = cluster_df.dropna()

cluster_df.shape

(52415, 17)

In [19]:
cluster_df.to_csv(
    "../outputs/clustering_ready_dataset.csv",
    index=False
)

## Selected Clustering Features

The selected features represent four main aspects of energy consumption behaviour:

1. Energy demand:
- Zone_1_Power_Consumption
- Zone_2_Power_Consumption
- Zone_3_Power_Consumption

2. Time-based behaviour:
- Hour
- Day_of_Week
- Month
- Is_Weekend
- Is_Peak_Hour

3. Environmental influence:
- Temperature
- Humidity
- Wind_Speed

4. Consumption trends:
- Lag features
- 24-hour rolling mean features

These features were selected because they describe energy usage patterns and allow clustering algorithms to identify similar consumption behaviours.